image: linbit/linstor-build

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - gradle -PoverrideVersion= getProtoc

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - tools

build:
  stage: build
  script:
    - gradle -PversionOverride= assemble
  artifacts:
    paths:
      - build/distributions/linstor-server.tar
    expire_in: 4 days

test:
  stage: test
  script:
    - JAVA_OPTS="-ea" gradle -PversionOverride= test
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml

deploy:
  stage: deploy
  dependencies:
    - build
  before_script:
    - echo "DEPLOY"
  script:
    - cp Dockerfile.test-controller Dockerfile
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/linstor/linstor-server/controller:latest .
    - docker push $CI_REGISTRY/linstor/linstor-server/controller:latest
  tags:
    - shell
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
